#!/usr/bin/env node
/**
 * Module dependencies. 
 */

var
    path   = require('path'),
    http   = require('http'),
    utils  = path.join(__dirname, '/utils/'),
    config = require(utils + 'nconf'),
    logger = require(utils + 'winston')(module),
    app    = require(utils + 'app_express');

config.set('serverRoot', __dirname);
config.save(function (err) {
  if (err) {
    logger.error(err.message);
    return;
  }
  logger.info('Config saved successfully!');
});

/**
 * Get port from environment and store in Express.
 */
var port = normalizePort(process.env.PORT || config.get('port') || 3000);
app.set('port', port);

/**
 * Create HTTP server.
 */
var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */
server.listen(port);
server.on('listening', function () {
  logger.info('Express server listening on port ' + app.get('port'));
});

/**
 * Normalize a port into a number, string, or false.
 */
function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}
