#!/usr/bin/env node
/**
 * Module dependencies.
 */
var
    utils  = process.cwd() + '/utils/',
    config = require(utils + 'nconf'),
    log    = require(utils + 'winston')(module),
    app    = require(utils + 'app_express'),
    http   = require('http');

/**
 * Get port from environment and store in Express.
 */
var port = normalizePort(process.env.PORT || config.get('port') || 3000);
app.set('port', port);

/**
 * Create HTTP server.
 */
var server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */
server.listen(port);
server.on('listening', function () {
  log.info('Express server listening on port ' + app.get('port'));
});

/**
 * Normalize a port into a number, string, or false.
 */
function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    // named pipe
    return val;
  }

  if (port >= 0) {
    // port number
    return port;
  }

  return false;
}
